//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID { get; set; }
        public string Bank_Name { get; set; }
        public byte[] Account_Name { get; set; }
        public string Account_No { get; set; }
        public string Account_Type { get; set; }
        public Nullable<decimal> Openning__Balance { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<decimal> Credit_Limit { get; set; }
        public Nullable<decimal> Current_Balance { get; set; }
    }
}
