//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal_Details
    {
        public int ID { get; set; }
        public Nullable<int> Journal_ID { get; set; }
        public Nullable<int> SNO { get; set; }
        public Nullable<int> Sub_Account_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Narration { get; set; }
    
        public virtual Journal Journal { get; set; }
        public virtual Sub_Accounts Sub_Accounts { get; set; }
    }
}
