//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSDBEntities : DbContext
    {
        public POSDBEntities()
            : base("name=POSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Barcode> Barcodes { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Customer_Sale> Customer_Sale { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Free_Product> Free_Product { get; set; }
        public DbSet<Gift> Gifts { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public DbSet<Journal_Details> Journal_Details { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Main_Accounts> Main_Accounts { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Product_Supplier> Product_Supplier { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<Sub_Accounts> Sub_Accounts { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Support> Supports { get; set; }
    }
}
