//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Product_Supplier = new HashSet<Product_Supplier>();
        }
    
        public int ID { get; set; }
        public int Address_ID { get; set; }
        public string Company_Name { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Designation { get; set; }
        public string Email { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Product_Supplier> Product_Supplier { get; set; }
    }
}
