//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntityDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Customer_Sale = new HashSet<Customer_Sale>();
            this.Free_Product = new HashSet<Free_Product>();
        }
    
        public int Invoice_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Journal_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Customer_Sale> Customer_Sale { get; set; }
        public virtual ICollection<Free_Product> Free_Product { get; set; }
        public virtual Journal Journal { get; set; }
    }
}
